import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Layout from "@/components/layout/Layout";

// const inter = Inter({ subsets: ["latin"] });

const regularFont = localFont({
  src: "../../public/fonts/Lato-Regular.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={regularFont.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
